### ISSUE TITLE
please review the code 

### ISSUE THREAD

**Issue by zt-luo** [orobotix/seadrone-developer-api#5]
https://github.com/orobotix/seadrone-developer-api/blob/b10da66275156580605f7dcebf37e689387d4419/udpUser/CUDPCommUser.cpp#L290

udpUser/CUDPCommUser.cpp: In member function 'void orobotix::CUDPCommUser::updateUserCommandData()':
udpUser/CUDPCommUser.cpp:291:41: warning: iteration 3 invokes undefined behavior [-Waggressive-loop-o             ptimizations]
       commandData_.c_forces_moments_[i] = robot_data_->c_forces_moments_[i];
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
udpUser/CUDPCommUser.cpp:290:23: note: within this loop
     for (int i = 0; i < 6; i++) {
                     ~~^~~

we got this warning , when we compile the code . please review the code.

**Comment by LukeAllen** [comment]
Good catch. That array has changed from length 6 to length 3. The problem should be fixed now.
